config/routes.rb
LogoApp::Application.routes.draw do
  get "/logos", :controller=>"Logos", :action=>"index", :as=>"logos"
  post "/logos", :controller=>"Logos", :action=>"create"

  get "/logos/new", :controller=>"Logos", :action=>"new", :as=>"new_logo"

  get "/logos/:id/edit", :controller=>"Logos", :action=>"edit", :as=>"edit_logo"

  get "/logos/:id", :controller=>"Logos", :action=>"show", :as=>"logo"
  put "/logos/:id", :controller=>"Logos", :action=>"update"
  delete "/logos/:id", :controller=>"Logos", :action=>"destroy"
end

app/models/logo.rb
class Logo < ActiveRecord::Base
  attr_accessible :title, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logos_controller.rb
class LogosController < ApplicationController

def new
	@logo = Logo.new
end

def create
	@logo = Logo.new(params[:logo])
	if @logo.save
		redirect_to logos_url
	else
		render 'new'
	end
end

def index
	@logos = Logo.all
end

def show
	@logo = Logo.find_by_id(params[:id])
end

def destroy
	p = Logo.find_by_id(params[:id])
	p.destroy
	redirect_to logos_url
end

def edit
	@logo = Logo.find_by_id(params[:id])
end

def update
	@logo = Logo.find_by_id(params[:id])
	@logo.url = params[:logo][:url]
	@logo.title = params[:logo][:title]
	if @logo.save
		redirect_to logos_url
	else
		render 'edit'
	end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logos/_form.html.erb
<%= form_for @logo do |logo| %>

	 <%= logo.label :url, "Enter Logo URL:" %>
	 <%= logo.text_field :url, :size=>75 %>

	 <%= logo.label :title, "Title of Logo:" %>
	 <%= logo.text_field :title, :size=>75 %>

	 <%= logo.submit %>
	 <%= link_to "Home", logos_url %>

<% end %>

app/views/logos/edit.html.erb
<h1>Edit Your Logo</h1>

<%= render 'form' %>

app/views/logos/index.html.erb
<h1>Logo Gallery</h1>

<%= link_to "Add a New Logo", new_logo_url %>

<ul>
<% @logos.each do |logo| %>
	<li>
		<%= link_to image_tag(logo.url, :width=>200), logo_url(logo.id) %>
		<%= link_to "Edit", edit_logo_url(logo.id) %>
		<%= link_to "Delete", logo_url(logo.id), :method=>"delete" %>
	</li>	
<% end %>
</ul>
	

app/views/logos/new.html.erb
<h1>Add a new logo:</h1>

<%= render 'form' %>

app/views/logos/show.html.erb
<h3><%= @logo.title %></h3>
<nav>
	<%= link_to "Edit", edit_logo_url(@logo.id) %>
	<%= link_to "Delete", logo_url(@logo.id), :method=>"delete" %>
</nav>
<%= link_to "Back", logos_url %>
<%= image_tag(@logo.url) %>